
import React from 'react';
import PageLayout from '@/components/PageLayout';
import GuideContent from '@/components/GuideContent';
import BreadcrumbNavigation from '@/components/BreadcrumbNavigation';

const PerformanceMetricsExplained = () => {
  const breadcrumbItems = [
    { label: 'Home', href: '/' },
    { label: 'Performance', href: '/performance' },
    { label: 'Performance Metrics Explained' },
  ];

  return (
    <PageLayout title="Performance Metrics Explained">
      <GuideContent title="Performance Metrics Explained" breadcrumbs={<BreadcrumbNavigation items={breadcrumbItems} />}>
        <div className="prose prose-invert max-w-none">
          <p className="text-lg mb-6">
            Understanding how your algorithm performs is crucial for long-term trading success. Tezaoro provides a suite of industry-standard performance metrics to help you evaluate and compare strategies with confidence.
          </p>
          
          <h2 className="text-2xl font-bold mt-8 mb-4">Key Metrics:</h2>
          
          <h3 className="text-xl font-bold mt-6 mb-2">Total Return:</h3>
          <p className="mb-4">
            The overall percentage gain or loss generated by your algorithm over a selected period.
          </p>
          
          <h3 className="text-xl font-bold mt-6 mb-2">Annualized Return:</h3>
          <p className="mb-4">
            The average yearly return, which allows for easy comparison between strategies with different timeframes.
          </p>
          
          <h3 className="text-xl font-bold mt-6 mb-2">Sharpe Ratio:</h3>
          <p className="mb-4">
            Measures risk-adjusted returns by comparing the excess return of your algorithm to its volatility. A higher Sharpe ratio indicates better risk-adjusted performance.
          </p>
          
          <h3 className="text-xl font-bold mt-6 mb-2">Maximum Drawdown:</h3>
          <p className="mb-4">
            The largest observed loss from a peak to a trough, indicating the worst-case scenario for capital loss during the strategy's run.
          </p>
          
          <h3 className="text-xl font-bold mt-6 mb-2">Win Rate:</h3>
          <p className="mb-4">
            The percentage of profitable trades out of the total number of trades executed.
          </p>
          
          <h3 className="text-xl font-bold mt-6 mb-2">Average Trade Duration:</h3>
          <p className="mb-4">
            The mean length of time each trade is held, useful for understanding the strategy's trading frequency and risk exposure.
          </p>
          
          <h3 className="text-xl font-bold mt-6 mb-2">Volatility:</h3>
          <p className="mb-4">
            Shows how much the returns fluctuate, helping you assess the risk profile of your algorithm.
          </p>
          
          <p className="text-lg mt-6">
            Each metric is calculated in real-time and can be viewed for any selected period in your dashboard.
          </p>
        </div>
      </GuideContent>
    </PageLayout>
  );
};

export default PerformanceMetricsExplained;
