
import React from 'react';
import ProcessStep from './ProcessStep';
import { 
  Database, 
  Code, 
  Terminal, 
  Zap, 
  Cpu, 
  TrendingUp, 
  Shield, 
  ArrowRight, 
  BarChart2, 
  LineChart 
} from 'lucide-react';

const ProcessStepsSection = () => {
  const processSteps = [
    {
      stepNumber: 1,
      title: "Data Collection & Analysis",
      description: "Our system continuously gathers vast amounts of market data from multiple sources. This includes:",
      features: [
        { icon: Database, text: "Historical price data across multiple timeframes" },
        { icon: LineChart, text: "Market volatility metrics and order book data" },
        { icon: BarChart2, text: "Economic indicators and sentiment analysis" }
      ],
      icon: Database,
      reverse: false
    },
    {
      stepNumber: 2,
      title: "AI Model Training",
      description: "Our proprietary AI models are trained on this vast dataset to identify patterns and generate trading signals. The AI system:",
      features: [
        { icon: Code, text: "Uses multiple machine learning approaches including deep learning and reinforcement learning" },
        { icon: Terminal, text: "Continuously retrains with new market data" },
        { icon: Zap, text: "Adapts to changing market conditions" }
      ],
      icon: Cpu,
      reverse: true
    },
    {
      stepNumber: 3,
      title: "Strategy Implementation",
      description: "The trading signals generated by our AI models are converted into executable trading strategies with built-in risk management:",
      features: [
        { icon: TrendingUp, text: "Strategies diversified across different asset classes and timeframes" },
        { icon: Shield, text: "Automated risk management with position sizing and stop-loss mechanisms" },
        { icon: ArrowRight, text: "Real-time execution with minimal latency" }
      ],
      icon: TrendingUp,
      reverse: false
    }
  ];

  return (
    <div className="space-y-16 mb-20">
      {processSteps.map((step, index) => (
        <ProcessStep key={index} {...step} />
      ))}
    </div>
  );
};

export default ProcessStepsSection;
