// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfzeegaepscycaaciviz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmemVlZ2FlcHNjeWNhYWNpdml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MjY0NDAsImV4cCI6MjA2NDIwMjQ0MH0.GLFPR_AdtnruTpIXs_en5R1JLXML3avnqNEwJK6hUdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);